######################################################################
# Automatically generated by qmake (2.01a) Fr. J�n 19 19:09:46 2018
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

LIBS += -lzmq
QMAKE_CXXFLAGS += -std=c++0x
